# combine_spirv_headers.cmake — concatenate two embed_spirv-generated headers
# into a single header the renderer includes (#include "shaders/test_scene_shaders.h").
#
# Invoked via `cmake -P` with: -DOUT=<final.h> -DVERT_H=<vert.h> -DFRAG_H=<frag.h>
# Each input already carries `#pragma once` + the uint32 array + a _size constant;
# we strip the duplicate `#pragma once`/include lines from the second and emit one
# guarded header.

if(NOT DEFINED OUT OR NOT DEFINED VERT_H OR NOT DEFINED FRAG_H)
  message(FATAL_ERROR "combine_spirv_headers: OUT, VERT_H and FRAG_H are required")
endif()

file(READ "${VERT_H}" _vert)
file(READ "${FRAG_H}" _frag)

# Drop leading '#pragma once' and '#include <cstdint>' from each fragment; we emit
# our own header preamble once.
string(REGEX REPLACE "#pragma once\n" "" _vert "${_vert}")
string(REGEX REPLACE "#include <cstdint>\n" "" _vert "${_vert}")
string(REGEX REPLACE "#pragma once\n" "" _frag "${_frag}")
string(REGEX REPLACE "#include <cstdint>\n" "" _frag "${_frag}")

set(_out "// Auto-generated by cmake/combine_spirv_headers.cmake. DO NOT EDIT.\n")
string(APPEND _out "#pragma once\n#include <cstdint>\n\n")
string(APPEND _out "${_vert}\n")
string(APPEND _out "${_frag}\n")

file(WRITE "${OUT}" "${_out}")
message(STATUS "combine_spirv_headers: wrote ${OUT}")
