# embed_spirv.cmake — convert a SPIR-V binary into a C++ header exposing a
# `static const uint32_t <SYMBOL>[]` array (and a <SYMBOL>_size count).
#
# Invoked via `cmake -P cmake/embed_spirv.cmake` with:
#   -DSPV_IN=<path to .spv>  -DHEADER_OUT=<path to .h>  -DSYMBOL=<C identifier>
#
# SPIR-V is a stream of little-endian 32-bit words; we read the file as hex and
# regroup into uint32 literals so vkCreateShaderModule can consume the array
# directly (pCode = array, codeSize = sizeof(array)). No run-time file I/O.

if(NOT DEFINED SPV_IN OR NOT DEFINED HEADER_OUT OR NOT DEFINED SYMBOL)
  message(FATAL_ERROR "embed_spirv: SPV_IN, HEADER_OUT and SYMBOL are required")
endif()

file(READ "${SPV_IN}" _hex HEX)
string(LENGTH "${_hex}" _hexlen)
math(EXPR _bytes "${_hexlen} / 2")
if(NOT _bytes GREATER 0)
  message(FATAL_ERROR "embed_spirv: ${SPV_IN} is empty")
endif()
math(EXPR _rem "${_bytes} % 4")
if(NOT _rem EQUAL 0)
  message(FATAL_ERROR "embed_spirv: ${SPV_IN} size (${_bytes}) is not a multiple of 4 (not SPIR-V words)")
endif()
math(EXPR _words "${_bytes} / 4")

set(_out "// Auto-generated by cmake/embed_spirv.cmake from ${SPV_IN}. DO NOT EDIT.\n")
string(APPEND _out "#pragma once\n#include <cstdint>\n\n")
string(APPEND _out "static const uint32_t ${SYMBOL}[] = {\n")

set(_line "    ")
set(_col 0)
math(EXPR _last "${_words} - 1")
foreach(_w RANGE 0 ${_last})
  math(EXPR _off "${_w} * 8")
  # Little-endian: bytes b0 b1 b2 b3 -> word 0xb3b2b1b0.
  string(SUBSTRING "${_hex}" "${_off}" 8 _grp)
  string(SUBSTRING "${_grp}" 0 2 _b0)
  string(SUBSTRING "${_grp}" 2 2 _b1)
  string(SUBSTRING "${_grp}" 4 2 _b2)
  string(SUBSTRING "${_grp}" 6 2 _b3)
  string(APPEND _line "0x${_b3}${_b2}${_b1}${_b0}u,")
  math(EXPR _col "${_col} + 1")
  if(_col EQUAL 8)
    string(APPEND _out "${_line}\n")
    set(_line "    ")
    set(_col 0)
  else()
    string(APPEND _line " ")
  endif()
endforeach()
if(_col GREATER 0)
  string(APPEND _out "${_line}\n")
endif()

string(APPEND _out "};\n")
string(APPEND _out "static const uint32_t ${SYMBOL}_size = sizeof(${SYMBOL});\n")

file(WRITE "${HEADER_OUT}" "${_out}")
message(STATUS "embed_spirv: wrote ${HEADER_OUT} (${_words} words, symbol ${SYMBOL})")
